version: '3.4'
services:
# MYSQL
  db:
    container_name: ${MYSQL_CONTAINER_NAME:-wp_db}
    image: "mysql:${MYSQL_VERSION:-5.7}"
    volumes:
      - './data/mysql:/var/lib/mysql'
    ports:
      - 18766:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME:-wordpress_db}
      MYSQL_USER: ${DB_USER:-wordpress_user}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD:-wordpress_password}
    networks:
      - ${WP_NETWORK:-wpsite}
# WORDPRESS
  wordpress:
    container_name: "${WORDPRESS_CONTAINER_NAME:-wp}"
    depends_on:
      - db
    image: 'wordpress:latest'
    ports:
      - "${WP_PORT:-88}:80"
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: ${DB_USER:-wordpress_user}
      WORDPRESS_DB_PASSWORD: ${DB_USER_PASSWORD:-wordpress_password}
      WORDPRESS_DB_NAME: ${DB_NAME:-wordpress_db}
    volumes:
      - "./data/wordpress:/var/www/html"
      - "./plugins:/var/www/html/wp-content/plugins"
      - "./themes:/var/www/html/wp-content/themes"
    networks:
      - "${WP_NETWORK:-wpsite}"
# PHPMYADMIN
  phpmyadmin:
    container_name: "${PHPMYADMIN_CONTAINER_NAME:-phpmyadmin_wp}"
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "${PHPMYADMIN_PORT:-89}:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root} 
    networks:
      - "${WP_NETWORK:-wpsite}"
networks:
  wpnetwork1:
  